from __future__ import annotations

from typing import Any


SOURCE_TIERS: list[dict[str, Any]] = [
    {
        "tier": 1,
        "name": "realtime_trading",
        "label": "真正即時行情與交易資料",
        "uses": ["盤中即時報價", "五檔", "逐筆", "下單", "改單", "刪單", "成交回報", "庫存", "損益", "帳務"],
        "priority_sources": [
            "正式券商 API",
            "富邦 Neo API",
            "永豐 Shioaji",
            "元大 SPARK API",
            "TWSE/TPEx/TAIFEX 授權即時行情",
        ],
        "current_status": "not_connected",
        "guardrail": "沒有券商 API 時只能分析、提醒、模擬交易、半自動交易建議，不能正式自動下單。",
    },
    {
        "tier": 2,
        "name": "official_public",
        "label": "官方公開資料",
        "uses": [
            "股票清單",
            "歷史 K 線",
            "盤後資料",
            "法人資料",
            "融資融券",
            "財報",
            "月營收",
            "重大訊息",
            "公司基本資料",
            "股利",
            "除權息",
            "集保股權分散",
            "期貨三大法人",
            "選擇權 Put/Call Ratio",
        ],
        "priority_sources": ["TWSE OpenAPI", "TPEx OpenAPI", "MOPS", "TDCC", "TAIFEX"],
        "current_status": "partially_implemented",
        "guardrail": "官方公開資料是歷史、盤後、財報與公告資料的優先來源。",
    },
    {
        "tier": 3,
        "name": "auxiliary",
        "label": "輔助資料",
        "uses": ["新聞", "產業趨勢", "國際市場", "總經", "社群情緒", "匯率", "商品", "摘要"],
        "priority_sources": ["FinMind", "Yahoo Finance", "Google News", "鉅亨網", "MoneyDJ", "工商時報", "經濟日報", "美國市場資料"],
        "current_status": "partially_implemented",
        "guardrail": "新聞資料不可當作價格資料唯一來源，必須與官方價格、財報、公告交叉驗證。",
    },
]


DATA_MODULES: list[dict[str, Any]] = [
    {
        "name": "securities_master",
        "label": "股票主檔",
        "fields": [
            "symbol",
            "name",
            "market",
            "listing_type",
            "industry",
            "trade_unit",
            "day_trade_eligible",
            "margin_eligible",
            "is_etf",
            "is_warrant",
            "list_date",
            "trading_status",
        ],
        "source_tier": 2,
        "implementation": {"status": "implemented", "api": "/api/securities/master", "model": "SecurityMasterItem"},
    },
    {
        "name": "real_time_quotes",
        "label": "即時行情",
        "fields": [
            "symbol",
            "time",
            "last_price",
            "change",
            "change_percent",
            "last_trade_size_lots",
            "volume",
            "turnover",
            "inner_outer",
            "bid_ask_1_to_5",
            "best_bid",
            "best_ask",
            "high",
            "low",
            "open",
            "previous_close",
            "limit_up",
            "limit_down",
            "trading_status",
            "exchange_timestamp",
            "freshness",
            "sequence",
        ],
        "source_tier": 1,
        "implementation": {
            "status": "implemented",
            "api": "/api/realtime/quote/{symbol}",
            "stream": "/api/realtime/stream/{symbol}",
            "schema_version": "stock_ai.realtime_quote.v1",
            "providers": ["TWSE MIS", "Fugle licensed market data"],
        },
    },
    {
        "name": "intraday_candles",
        "label": "盤中 K 線",
        "fields": [
            "symbol",
            "trading_date",
            "bucket_start",
            "bucket_end",
            "open",
            "high",
            "low",
            "close",
            "volume_lots",
            "turnover",
            "source_ids",
            "revision_ids",
        ],
        "periods": ["1m", "5m", "15m", "30m", "60m"],
        "source_tier": 1,
        "implementation": {
            "status": "implemented",
            "api": "/api/intraday/candles/{symbol}",
            "dates_api": "/api/intraday/candles/{symbol}/dates",
            "schema_version": "stock_ai.intraday_candles.v1",
            "base_timeframe": "1m",
            "reconstruction": "Asia/Taipei 09:00 anchored aggregation",
            "providers": [
                "Fugle licensed market data",
                "Yahoo Finance research-only fallback",
                "TWSE MIS observed quote samples",
            ],
        },
    },
    {
        "name": "ohlcv",
        "label": "歷史 K 線",
        "fields": ["open", "high", "low", "close", "volume", "turnover", "vwap"],
        "periods": ["tick", "1s", "5s", "1m", "5m", "15m", "30m", "1d", "1w", "1mo"],
        "source_tier": 2,
        "implementation": {
            "status": "revisioned_raw_and_adjusted_daily_history_implemented",
            "api": "/api/market/{symbol}/history",
            "unified_api": "/api/data/ui/v1/market/{symbol}/history",
            "schema_version": "stock_ai.daily_history.v1",
            "storage_schema_version": 27,
            "model": "PricePoint",
            "price_bases": [
                "unadjusted",
                "forward_adjusted",
                "backward_adjusted",
            ],
            "adjustment_schema_version": "stock_ai.price_adjustment.v1",
            "adjustment_factor_method": "official_reference_price_ratio",
            "adjustment_sources": [
                "twse_official_web",
                "tpex_official_web",
            ],
            "pagination": "exclusive trade-date cursor, maximum 5000 rows",
        },
    },
    {
        "name": "liquidity",
        "label": "流動性與可交易性",
        "fields": [
            "turnover",
            "turnover_rate",
            "average_volume",
            "average_turnover",
            "bid_ask_spread",
            "estimated_slippage",
            "tradability",
        ],
        "source_tier": 2,
        "implementation": {
            "status": "source_attributed_liquidity_assessment_implemented",
            "api": "/api/market/{symbol}/liquidity",
            "unified_api": "/api/data/ui/v1/market/{symbol}/liquidity",
            "schema_version": "stock_ai.liquidity_assessment.v1",
            "storage_schema_version": 30,
            "history_sources": ["twse_official_web", "tpex_official_web"],
            "quote_sources": ["twse_mis", "fugle"],
            "share_sources": ["twse_openapi", "tpex_openapi"],
            "missing_data_policy": "unavailable_fields_remain_null_and_block_complete_assessment",
        },
    },
    {
        "name": "market_indices",
        "label": "大盤與類股",
        "fields": ["weighted_index", "tpex_index", "sector_indices", "futures_indices"],
        "coverage": ["加權", "櫃買", "電子", "金融", "半導體", "AI 伺服器", "航運", "鋼鐵", "塑化", "生技", "營建", "觀光", "ETF", "期貨"],
        "source_tier": 2,
        "implementation": {"status": "partially_implemented", "api": "/api/overview/indices", "taifex_contract": "/api/official/taifex/derivatives-summary"},
    },
    {
        "name": "institutional_investors",
        "label": "三大法人",
        "fields": ["foreign_net", "trust_net", "dealer_net", "dealer_hedge_net", "total_net", "streak_days", "holding_ratio_change"],
        "source_tier": 2,
        "implementation": {"status": "implemented", "api": "/api/flow/institutional", "model": "InstitutionalFlowItem"},
    },
    {
        "name": "chip_data",
        "label": "籌碼",
        "fields": ["margin_balance", "short_balance", "margin_short_ratio", "borrow_sell", "day_trade_ratio", "broker_branch_flow", "tdcc_distribution", "major_holder_1000_lot_ratio", "holder_400_lot_ratio", "small_shareholder_count"],
        "source_tier": 2,
        "implementation": {
            "status": "partial_margin_and_tdcc_weekly_history_implemented",
            "api": "/api/flow/margin",
            "tdcc_api": "/api/official/tdcc/holding-distribution",
            "tdcc_history_api": "/api/data/ui/v1/flow/chip/tdcc-history",
            "tdcc_import_api": "/api/official/tdcc/holding-distribution/import",
            "tdcc_csv_import_api": "/api/official/tdcc/holding-distribution/import-csv",
            "model": "MarginTradingItem",
        },
    },
    {
        "name": "fundamentals",
        "label": "基本面",
        "fields": ["monthly_revenue", "yoy", "mom", "eps", "roe", "roa", "gross_margin", "operating_margin", "net_margin", "cash_flow", "debt_ratio", "pe", "pb", "yield"],
        "source_tier": 2,
        "implementation": {"status": "monthly_revenue_implemented", "api": "/api/fundamentals/revenue", "model": "RevenueItem"},
    },
    {
        "name": "company_events",
        "label": "公司事件",
        "fields": ["material_event", "earnings_call", "shareholder_meeting", "ex_dividend", "capital_reduction", "capital_increase", "merger", "attention_stock", "disposition_stock"],
        "source_tier": 2,
        "implementation": {
            "status": "mops_official_cache_available",
            "api": "/api/market/{symbol}/events",
            "mops_api": "/api/official/mops/company-events",
            "mops_import_api": "/api/official/mops/company-events/import",
            "mops_csv_import_api": "/api/official/mops/company-events/import-csv",
            "model": "EventItem",
        },
    },
    {
        "name": "news",
        "label": "新聞",
        "fields": ["title", "source", "published_at", "related_symbols", "category", "sentiment", "event_type", "credibility", "official_verified"],
        "categories": ["company", "industry", "macro", "international", "policy", "analyst"],
        "source_tier": 3,
        "implementation": {"status": "implemented", "api": "/api/news/center", "model": "NewsItem"},
    },
    {
        "name": "portfolio",
        "label": "投資組合",
        "fields": ["holdings", "cost", "latest_price", "unrealized_pnl", "realized_pnl", "return_pct", "position_weight", "risk_exposure", "today_pnl", "total_assets", "cash"],
        "source_tier": 1,
        "implementation": {"status": "preview_only", "api": "/api/assets/summary", "model": "AssetWorkspace"},
    },
    {
        "name": "orders_executions",
        "label": "委託與成交",
        "fields": ["order_id", "symbol", "side", "price", "quantity", "condition", "time_in_force", "status", "fill_price", "fill_quantity", "fee", "tax", "executed_at"],
        "source_tier": 1,
        "implementation": {"status": "disabled_until_broker_api", "api": "/api/trading/preview", "guardrail": "沒有正式券商 API 不啟用正式委託與成交。"},
    },
    {
        "name": "ai_signals",
        "label": "交易訊號",
        "fields": ["symbol", "signal_time", "signal_type", "action", "confidence", "technical_reason", "chip_reason", "fundamental_reason", "news_reason", "risk", "entry_price", "stop_loss", "take_profit", "invalid_condition"],
        "source_tier": 3,
        "implementation": {"status": "implemented_as_strategy_signals", "api": "/api/open-stock-ai/signals", "schema": "open_stock_ai.trading_signal.v1"},
    },
]


APP_FEATURES: list[dict[str, Any]] = [
    {"key": "home", "label": "A. 首頁總覽", "required": ["indices", "breadth", "turnover", "sector_strength", "rankings", "major_news", "daily_summary"], "status": "partial"},
    {"key": "watchlist", "label": "B. 自選股", "required": ["groups", "quotes", "change_volume_flow_margin_news", "custom_alerts"], "status": "partial"},
    {"key": "stock_page", "label": "C. 個股頁", "required": ["quote_orderbook", "intraday_chart", "kline", "technical_indicators", "chips", "fundamentals", "news_events", "score", "trade_plan"], "status": "partial"},
    {"key": "monitor", "label": "D. 看盤功能", "required": ["quotes", "orderbook", "ticks", "inner_outer", "large_trade", "surge_drop", "volume_anomaly", "limit_monitor", "sector_heatmap", "intraday_reading"], "status": "partial"},
    {"key": "screener", "label": "E. 選股器", "required": ["technical", "chip", "fundamental", "event", "risk"], "status": "partial"},
    {"key": "news_center", "label": "F. 新聞中心", "required": ["market_news", "company_news", "industry_news", "international_news", "mops_events", "summary", "impact_judgement", "price_reaction"], "status": "partial"},
    {"key": "chips", "label": "G. 法人與籌碼中心", "required": ["three_institutions", "rankings", "streaks", "margin_short", "borrow", "tdcc", "broker_branch"], "status": "partial"},
    {"key": "fundamentals", "label": "H. 財報與基本面中心", "required": ["monthly_revenue", "quarterly_reports", "annual_reports", "eps", "roe", "margins", "cash_flow", "dividends", "valuation_rivers", "peer_compare"], "status": "partial"},
    {"key": "trading", "label": "I. 交易功能", "required": ["broker_api_required", "orders", "modify_cancel", "fills", "positions", "pnl", "settlement", "fees"], "status": "preview_only"},
    {"key": "assistant", "label": "J. 交易輔助", "required": ["pre_market", "intraday_alerts", "post_market_review", "trade_plan", "risk_advice", "backtest", "paper_trade", "journal", "reflection"], "status": "partial"},
    {"key": "risk", "label": "K. 風控功能", "required": ["single_loss", "daily_loss", "position_cap", "industry_exposure", "leverage", "day_trade_limit", "loss_pause", "blacklist", "event_risk"], "status": "implemented_core"},
    {"key": "assets", "label": "L. 帳務與資產", "required": ["total_assets", "cash", "holdings_value", "today_pnl", "cumulative_pnl", "dividends", "settlement", "statement", "trades", "taxes"], "status": "preview_only"},
    {"key": "notifications", "label": "M. 通知系統", "required": ["price", "change", "large_trade", "institutional", "material_event", "news", "signal", "risk", "fill", "telegram", "line", "email", "push"], "status": "telegram_line_explicit_send_available"},
]


UPDATE_SCHEDULE: list[dict[str, Any]] = [
    {"window": "08:00-08:50", "phase": "pre_market", "tasks": ["更新美股、費半、ADR、匯率、期貨", "抓取重大新聞", "檢查 MOPS 重大訊息", "產生盤前觀察清單"]},
    {"window": "09:00-13:30", "phase": "intraday", "tasks": ["使用授權行情或券商 API streaming", "監控自選股、持股、候選股", "偵測急漲急跌、爆量、突破、跌破、法人/籌碼異常"], "guardrail": "不可依賴慢速網頁爬蟲做秒級交易。"},
    {"window": "13:35-15:30", "phase": "post_close", "tasks": ["抓取官方收盤資料", "更新日 K", "更新三大法人、融資融券、成交排行", "產生收盤報告"]},
    {"window": "15:30-20:00", "phase": "after_hours", "tasks": ["更新月營收、財報、重大訊息", "更新新聞與產業資料", "更新回測資料", "反思今日交易與訊號品質"]},
    {"window": "weekly", "phase": "weekly", "tasks": ["更新 TDCC 集保股權分散", "檢查大戶比例、小股東人數、籌碼集中度", "產生週報"]},
]


DECISION_RULES: list[str] = [
    "不可只看單一資料做買賣決策。",
    "每個交易建議至少包含技術面、籌碼面、基本面、新聞/事件面、風險因素、進場價、停損價、停利價、失效條件、信心分數、資料來源與時間戳記。",
    "資料來源衝突時必須標記資料衝突，不能假裝確定。",
]


SAFETY_LIMITS: list[dict[str, Any]] = [
    {"code": "no_auto_order_without_broker_api", "rule": "沒有券商 API，不可以自動下單。", "enforced_by": ["ReadonlyWorkspaceMeta", "BrokerConnectionStatus", "runtime_governance"], "status": "enforced"},
    {"code": "no_mouse_broker_app_ordering", "rule": "不可以用模擬滑鼠點券商 App 的方式下單。", "enforced_by": ["architecture_boundary"], "status": "policy_declared"},
    {"code": "no_yahoo_google_as_sole_price_source", "rule": "不可以把 Google/Yahoo 爬蟲當成唯一行情來源。", "enforced_by": ["source_tiers", "MarketSummary data_source checks"], "status": "partially_enforced"},
    {"code": "risk_gate_required", "rule": "所有交易訊號都必須經過風控。", "enforced_by": ["RiskEngine", "open_stock_ai.risk_decision.v1"], "status": "enforced"},
    {"code": "validate_before_auto_trading", "rule": "自動交易前必須先通過回測、紙上交易、小資金實盤驗證。", "enforced_by": ["paper_only_mode", "backtest_research", "paper_executor"], "status": "enforced_for_current_mode"},
    {"code": "pre_order_checks", "rule": "下單前必須檢查價格、數量、庫存、現金、最大虧損、最大部位。", "enforced_by": ["TradingWorkspace", "RiskEngine"], "status": "preview_enforced"},
    {"code": "decision_reason_logging", "rule": "所有決策必須記錄原因，方便事後檢討。", "enforced_by": ["decision_log", "paper_order_payload"], "status": "enforced"},
]


MVP_PHASES: list[dict[str, Any]] = [
    {
        "phase": 1,
        "label": "第一版",
        "items": ["TWSE + TPEx 股票清單", "歷史日 K", "三大法人", "融資融券", "月營收", "重大訊息", "新聞摘要", "自選股", "每日選股報告", "Telegram/LINE 推播"],
        "status": "partially_implemented",
    },
    {
        "phase": 2,
        "label": "第二版",
        "items": ["即時行情", "盤中監控", "K 線圖與技術指標", "回測系統", "模擬交易"],
        "status": "partially_implemented",
    },
    {
        "phase": 3,
        "label": "第三版",
        "items": ["券商 API", "庫存", "帳務", "委託", "成交回報", "半自動下單", "自動下單與人工確認模式"],
        "status": "blocked_until_broker_api",
    },
]


def stock_app_requirement_contract() -> dict[str, Any]:
    module_names = {item["name"] for item in DATA_MODULES}
    return {
        "schema_version": "stock_ai.requirement_contract.v1",
        "method": "local_goal_objective_contract_projection",
        "source_tiers": SOURCE_TIERS,
        "data_modules": DATA_MODULES,
        "app_features": APP_FEATURES,
        "update_schedule": UPDATE_SCHEDULE,
        "decision_rules": DECISION_RULES,
        "safety_limits": SAFETY_LIMITS,
        "mvp_phases": MVP_PHASES,
        "coverage": {
            "source_tier_count": len(SOURCE_TIERS),
            "data_module_count": len(DATA_MODULES),
            "app_feature_count": len(APP_FEATURES),
            "schedule_window_count": len(UPDATE_SCHEDULE),
            "safety_limit_count": len(SAFETY_LIMITS),
            "mvp_phase_count": len(MVP_PHASES),
            "required_data_modules_present": sorted(module_names),
            "live_ordering_enabled": False,
            "broker_api_connected": False,
            "orders_executions_enabled": False,
            "schedule_guard_schema": "stock_ai.schedule_guard.v1",
            "schedule_guard_endpoint": "/api/system/schedule",
            "source_policy_schema": "stock_ai.source_policy.v1",
            "source_policy_endpoint": "/api/system/source-policy",
            "source_policy_evaluate_endpoint": "/api/system/source-policy/evaluate",
            "update_runner_schema": "stock_ai.update_runner.v1",
            "update_plan_endpoint": "/api/system/update-plan",
            "update_run_endpoint": "/api/system/update-run",
            "official_derivatives_schema": "stock_ai.official_derivatives.v1",
            "official_derivatives_endpoint": "/api/system/official-derivatives",
            "official_events_schema": "stock_ai.official_events.v1",
            "official_events_endpoint": "/api/system/official-events",
            "notification_send_endpoint": "/api/notifications/send",
            "mops_company_events_endpoint": "/api/official/mops/company-events",
            "mops_company_events_import_endpoint": "/api/official/mops/company-events/import",
            "mops_company_events_csv_import_endpoint": "/api/official/mops/company-events/import-csv",
            "tdcc_holding_distribution_endpoint": "/api/official/tdcc/holding-distribution",
            "tdcc_holding_distribution_import_endpoint": "/api/official/tdcc/holding-distribution/import",
            "tdcc_holding_distribution_csv_import_endpoint": "/api/official/tdcc/holding-distribution/import-csv",
            "taifex_derivatives_endpoint": "/api/official/taifex/derivatives-summary",
            "taifex_derivatives_import_endpoint": "/api/official/taifex/derivatives-summary/import",
            "taifex_derivatives_csv_import_endpoint": "/api/official/taifex/derivatives-summary/import-csv",
        },
    }
