from __future__ import annotations

from typing import Any, Awaitable, Callable

from .contracts import AgentRunContext


RollbackExecutor = Callable[[str, dict[str, Any], AgentRunContext], Awaitable[dict[str, Any]]]


class RollbackManager:
    """Restore a host-issued mutation token after failed post-validation.

    Only a result generated by the host's project mutation capability may carry
    a rollback token. The rollback itself still goes through the same Stock AI
    capability registry, never through provider text or direct filesystem I/O.
    """

    async def rollback_if_available(
        self,
        *,
        tool_name: str,
        result: dict[str, Any] | None,
        context: AgentRunContext,
        execute: RollbackExecutor,
    ) -> dict[str, Any] | None:
        if tool_name == "project.rollback_change" or not isinstance(result, dict):
            return None
        token = str(result.get("rollback_token") or "").strip()
        if not token or not tool_name.startswith("project."):
            return None
        restored = await execute("project.rollback_change", {"rollback_token": token}, context)
        return {
            "schema_version": "open_stock_ai.rollback_result.v1",
            "source_tool": tool_name,
            "rollback_token": token,
            "result": restored,
            "confirmed": bool(restored.get("confirmed") or restored.get("success")),
        }

